Repository CS2103-AY1819S2-W14-1/main, pull requests merged in 2019-03, with the labels that each got.

#34 Enhance Card class
  src/main/java/braintrain/commons/core/delete_me.txt
  src/main/java/braintrain/commons/exceptions/delete_me.txt
  src/main/java/braintrain/model/card/Card.java
  src/test/java/braintrain/model/card/CardTest.java
  src/test/java/braintrain/testutil/CardBuilder.java
  src/test/java/braintrain/testutil/TypicalCards.java
Labels: type.Epic

#30 Added User package
  src/main/java/braintrain/model/lesson/Lesson.java
  src/main/java/braintrain/model/user/CardData.java
  src/main/java/braintrain/model/user/User.java
Labels: priority.High, status.Ongoing

#39 Enhance Lesson and Card class
  src/main/java/braintrain/model/card/Card.java
  src/main/java/braintrain/model/card/exceptions/MissingCoreException.java
  src/main/java/braintrain/model/card/exceptions/MissingOptionalException.java
  src/main/java/braintrain/model/lesson/Lesson.java
  src/main/java/braintrain/model/lesson/exceptions/MissingCoreValueException.java
  src/main/java/braintrain/storage/CsvLessonsStorage.java
  src/main/java/braintrain/ui/delete_me.txt
  src/test/java/braintrain/model/LessonsTest.java
  src/test/java/braintrain/model/ModelManagerTest.java
  src/test/java/braintrain/model/card/CardTest.java
  src/test/java/braintrain/model/lesson/LessonTest.java
  src/test/java/braintrain/storage/CsvLessonsStorageTest.java
  src/test/java/braintrain/testutil/CardBuilder.java
  src/test/java/braintrain/testutil/LessonBuilder.java
  src/test/java/braintrain/testutil/TypicalCards.java
  src/test/java/braintrain/testutil/TypicalLessons.java
Labels: type.Epic

#45 Fix missing quiz tag and update DG user stories
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.Docs

#40 Session system and srscard model
  docs/UserGuide.adoc
  src/main/java/braintrain/model/card/SrsCard.java
  src/main/java/braintrain/model/session/Session.java
  src/main/java/braintrain/model/session/SrsCardsManager.java
Labels: type.Epic

#66 Update docs for updated organisation name
  README.adoc
  docs/ContactUs.adoc
Labels: priority.High

#77 Enhance Lesson class and refactor Card class
  src/main/java/seedu/address/model/card/Card.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/storage/CsvLessonsStorage.java
  src/test/java/seedu/address/model/card/CardTest.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
  src/test/java/seedu/address/testutil/CardBuilder.java
  src/test/java/seedu/address/testutil/LessonBuilder.java
  src/test/java/seedu/address/testutil/TypicalCards.java
  src/test/java/seedu/address/testutil/TypicalLessons.java
Labels: priority.High, type.Epic

#76 Update Quiz related docs, refactor quiz command to logic and add QuizHelpCommand
  README.adoc
  build.gradle
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/QuizAnswerCommandSequenceDiagram.pptx
  docs/diagrams/QuizModelComponentClassDiagram.pptx
  docs/diagrams/Ui.pptx
  docs/images/Architecture.png
  docs/images/LogicClassDiagram.png
  docs/images/QuizAnswerCommandSequenceDiagram.png
  docs/images/QuizModelClassDiagram.png
  docs/images/Ui.png
  docs/team/halcyoneee.adoc
  docs/templates/_header.html.slim
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/QuizAnswerCommand.java
  src/main/java/seedu/address/logic/commands/QuizCommand.java
  src/main/java/seedu/address/logic/commands/QuizHelpCommand.java
  src/main/java/seedu/address/logic/parser/QuizModeParser.java
  src/main/java/seedu/address/quiz/QuizModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/QuizAnswerCommandTest.java
  src/test/java/seedu/address/logic/commands/QuizCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/QuizHelpCommandTest.java
  src/test/java/seedu/address/logic/parser/QuizModeParserTest.java
Labels: type.Docs, type.Task

#75 V1.2 user
  src/main/java/seedu/address/commons/exceptions/CardDataImportException.java
  src/main/java/seedu/address/commons/exceptions/DuplicateCardDataException.java
  src/main/java/seedu/address/model/card/SrsCard.java
  src/main/java/seedu/address/model/session/SrsCardsManager.java
  src/main/java/seedu/address/model/user/CardSrsData.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/storage/UserImportExport.java
  src/test/java/seedu/address/model/user/CardDataTest.java
  src/test/java/seedu/address/model/user/UserTest.java
Labels: status.Ongoing

#96 Quiz v1.2
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/QuizStatusCommandSequenceDiagram.pptx
  docs/images/QuizStatusCommandSequenceDiagram.png
  docs/images/Ui.png
  docs/images/UiFirstLook.png
  docs/images/UiMockup.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/management/ExitCommand.java
  src/main/java/seedu/address/logic/commands/management/HelpCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizAnswerCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizHelpCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizStartCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizStatusCommand.java
  src/main/java/seedu/address/logic/parser/QuizModeParser.java
  src/main/java/seedu/address/model/modelmanager/quiz/Quiz.java
  src/main/java/seedu/address/model/modelmanager/quiz/QuizCard.java
  src/main/java/seedu/address/model/modelmanager/quiz/QuizModel.java
  src/main/java/seedu/address/model/modelmanager/quiz/QuizModelManager.java
  src/main/java/seedu/address/model/modelmanager/quiz/exceptions/NotInitialisedException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/QuizResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/braintrain_colour_32.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/QuizResultDisplay.fxml
  src/test/java/guitests/guihandles/QuizResultDisplayHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/management/AddLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/management/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/management/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/management/DeleteLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/management/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/management/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/management/HistoryCommandTest.java
  src/test/java/seedu/address/logic/commands/management/ListLessonsCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizAnswerCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/quiz/QuizHelpCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizStartCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizStatusCommandTest.java
  src/test/java/seedu/address/logic/parser/AddLessonParserTest.java
  src/test/java/seedu/address/logic/parser/QuizModeParserTest.java
  src/test/java/seedu/address/model/modelmanager/management/ManagementModelManagerTest.java
  src/test/java/seedu/address/model/modelmanager/quiz/QuizCardTest.java
  src/test/java/seedu/address/model/modelmanager/quiz/QuizManagementModelManagerTest.java
  src/test/java/seedu/address/model/modelmanager/quiz/QuizTest.java
  src/test/java/seedu/address/ui/QuizResultDisplayTest.java
Labels: priority.High

#86 Update DG
  docs/DeveloperGuide.adoc
  docs/diagrams/UserModelComponentClassDiagram.pptx
  docs/team/jeraldtsy.adoc
  src/main/java/seedu/address/model/user/CardSrsData.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/storage/CsvUserStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserImportExport.java
  src/main/java/seedu/address/storage/UserStorage.java
  src/test/java/seedu/address/model/user/CardDataTest.java
Labels: type.Docs

#97 Session V1.2
  docs/UserGuide.adoc
  docs/team/lallanachang.adoc
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/address/logic/commands/quiz/QuizStartCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/ManagementModeParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/main/java/seedu/address/logic/parser/Syntax.java
  src/main/java/seedu/address/model/modelmanager/quiz/QuizModel.java
  src/main/java/seedu/address/model/modelmanager/quiz/QuizModelManager.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SrsCardsManager.java
  src/main/java/seedu/address/model/srscard/SrsCard.java
  src/main/java/seedu/address/model/user/CardSrsData.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/management/AddLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/management/DeleteLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/management/ListLessonsCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizStartCommandTest.java
  src/test/java/seedu/address/logic/parser/ManagementModeParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/StartCommandParserTest.java
  src/test/java/seedu/address/model/modelmanager/quiz/QuizManagementModelManagerTest.java
  src/test/java/seedu/address/model/session/SessionTest.java
  src/test/java/seedu/address/model/session/SrsCardsManagerTest.java
  src/test/java/seedu/address/model/srscard/SrsCardTest.java
  src/test/java/seedu/address/testutil/CardBuilder.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
  src/test/java/seedu/address/testutil/SrsCardBuilder.java
Labels: priority.High

#102 Component Integration
  docs/UserGuide.adoc
  docs/images/UiFirstLook.png
  docs/team/eugenefdw.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/modelmanager/management/ManagementModel.java
  src/main/java/seedu/address/model/modelmanager/management/ManagementModelManager.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/storage/CsvLessonImportExport.java
  src/main/java/seedu/address/storage/CsvLessonsStorage.java
  src/main/java/seedu/address/storage/CsvUserStorage.java
  src/main/java/seedu/address/storage/LessonImportExport.java
  src/main/java/seedu/address/storage/LessonsStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserImportExport.java
  src/main/java/seedu/address/storage/UserStorage.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/management/AddLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/management/DeleteLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/management/ListLessonsCommandTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/modelmanager/management/ManagementModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
Labels: priority.High

#108 Quiz mid-v1.3
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/quiz/QuizAnswerCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizDifficultCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizHelpCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizStartCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizStatusCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/QuizModeParser.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/modelmanager/QuizModel.java
  src/main/java/seedu/address/model/modelmanager/QuizModelManager.java
  src/main/java/seedu/address/model/quiz/Quiz.java
  src/main/java/seedu/address/model/quiz/QuizCard.java
  src/main/java/seedu/address/model/quiz/QuizMode.java
  src/main/java/seedu/address/model/quiz/QuizUiDisplayFormatter.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/ui/MainPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/QuizResultDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/MainPanelHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/management/AddLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/management/DeleteLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/management/ListLessonsCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizAnswerCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/quiz/QuizDifficultCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizHelpCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizStartCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizStatusCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/QuizModeParserTest.java
  src/test/java/seedu/address/logic/parser/StartCommandParserTest.java
  src/test/java/seedu/address/model/modelmanager/QuizModelManagerTest.java
  src/test/java/seedu/address/model/quiz/QuizCardTest.java
  src/test/java/seedu/address/model/quiz/QuizTest.java
  src/test/java/seedu/address/model/quiz/QuizUiDisplayFormatterTest.java
  src/test/java/seedu/address/model/session/SessionTest.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
  src/test/java/seedu/address/ui/MainPanelTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/seedu/address/ui/QuizResultDisplayTest.java
Labels: priority.High, type.Bug

#106 Add check statements CSVUserStorage
  src/main/java/seedu/address/model/user/CardSrsData.java
  src/main/java/seedu/address/storage/CsvUserStorage.java
  src/test/java/seedu/address/model/user/CardSrsDataTest.java
  src/test/java/seedu/address/model/user/UserTest.java
Labels: priority.High

#109 Session mid-v1.3
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/quiz/QuizAnswerCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizStartCommand.java
  src/main/java/seedu/address/model/modelmanager/QuizModel.java
  src/main/java/seedu/address/model/modelmanager/QuizModelManager.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SrsCardsManager.java
  src/test/java/seedu/address/logic/commands/management/AddLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/management/DeleteLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/management/ListLessonsCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizAnswerCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizStartCommandTest.java
  src/test/java/seedu/address/logic/parser/StartCommandParserTest.java
  src/test/java/seedu/address/model/modelmanager/QuizModelManagerTest.java
  src/test/java/seedu/address/model/session/SessionTest.java
  src/test/java/seedu/address/model/session/SrsCardsManagerTest.java
Labels: priority.High

#129 Quiz v1.3 fix quiz end save logic and \quit
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/quiz/QuizAnswerCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizDifficultCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizHelpCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizQuitCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizStartCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizStatusCommand.java
  src/main/java/seedu/address/logic/parser/QuizModeParser.java
  src/main/java/seedu/address/model/modelmanager/QuizModel.java
  src/main/java/seedu/address/model/modelmanager/QuizModelManager.java
  src/main/java/seedu/address/model/quiz/Quiz.java
  src/main/java/seedu/address/model/quiz/QuizCard.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/user/CardSrsData.java
  src/main/java/seedu/address/storage/CsvUserStorage.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizAnswerCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizDifficultCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizHelpCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizQuitCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizStartCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizStatusCommandTest.java
  src/test/java/seedu/address/logic/parser/QuizModeParserTest.java
  src/test/java/seedu/address/model/modelmanager/QuizModelManagerTest.java
  src/test/java/seedu/address/model/modelmanager/QuizModelStub.java
  src/test/java/seedu/address/model/quiz/QuizCardTest.java
  src/test/java/seedu/address/model/quiz/QuizTest.java
  src/test/java/seedu/address/model/user/CardSrsDataTest.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
  src/test/java/seedu/address/testutil/TypicalSession.java
Labels: priority.High
