Repository CS2103-AY1819S2-W14-1/main, pull requests merged in 2019-04, with the labels that each got.

#133 Quiz v1.3: hint and difficult command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/QuizAnswerCommandSequenceDiagram.pptx
  docs/diagrams/QuizModelComponentClassDiagram.pptx
  docs/diagrams/QuizQuitCommandSequenceDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/LogicClassDiagram.png
  docs/images/QuizAnswerCommandSequenceDiagram.png
  docs/images/QuizModelClassDiagram.png
  docs/images/QuizQuitCommandSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/halcyoneee.adoc
  src/main/java/seedu/address/logic/commands/quiz/QuizAnswerCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizHelpCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizHintCommand.java
  src/main/java/seedu/address/logic/commands/quiz/QuizStartCommand.java
  src/main/java/seedu/address/logic/parser/QuizModeParser.java
  src/main/java/seedu/address/model/modelmanager/QuizModel.java
  src/main/java/seedu/address/model/modelmanager/QuizModelManager.java
  src/main/java/seedu/address/model/quiz/Quiz.java
  src/main/java/seedu/address/model/quiz/QuizCard.java
  src/main/java/seedu/address/model/quiz/QuizUiDisplayFormatter.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/ui/MainPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizHintCommandTest.java
  src/test/java/seedu/address/logic/commands/quiz/QuizStartCommandTest.java
  src/test/java/seedu/address/logic/parser/QuizModeParserTest.java
  src/test/java/seedu/address/model/modelmanager/QuizModelManagerTest.java
  src/test/java/seedu/address/model/modelmanager/QuizModelStub.java
  src/test/java/seedu/address/model/quiz/QuizCardTest.java
  src/test/java/seedu/address/model/quiz/QuizTest.java
  src/test/java/seedu/address/model/session/SessionTest.java
  src/test/java/seedu/address/ui/MainPanelTest.java
Labels: priority.High

#143 Update User Guide
  docs/UserGuide.adoc
Labels: type.Docs

#139 Update CsvUserStorage to sanitise input values
  src/main/java/seedu/address/storage/CsvUserStorage.java
  src/test/data/UserStorageTest/hashcodeZeroTest.csv
  src/test/data/UserStorageTest/numberOfAttemptsNegativeTest.csv
  src/test/data/UserStorageTest/streakNegativeTest.csv
  src/test/java/seedu/address/storage/CsvLessonListStorageTest.java
  src/test/java/seedu/address/storage/CsvUserStorageTest.java
Labels: severity.Low

#183 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/CsvUserStorage.pptx
  docs/images/CsvUserStorage.png
  docs/team/jeraldtsy.adoc
Labels: type.Docs

#185 Session v1.4
  docs/UserGuide.adoc
  docs/team/lallanachang.adoc
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/management/QuizStartCommand.java
  src/main/java/seedu/address/logic/parser/ManagementModeParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/main/java/seedu/address/logic/parser/Syntax.java
  src/main/java/seedu/address/model/modelmanager/QuizModel.java
  src/main/java/seedu/address/model/modelmanager/QuizModelManager.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SrsCardsManager.java
  src/main/java/seedu/address/model/srscard/SrsCard.java
  src/main/java/seedu/address/ui/MainPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/management/QuizStartCommandTest.java
  src/test/java/seedu/address/logic/parser/ManagementModeParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/StartCommandParserTest.java
  src/test/java/seedu/address/model/modelmanager/QuizModelManagerTest.java
  src/test/java/seedu/address/model/modelmanager/QuizModelStub.java
  src/test/java/seedu/address/model/session/SessionTest.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/MainPanelTest.java
  src/test/java/systemtests/QuizAnswerCommandSystemTest.java
Labels: type.Enhancement
